channels:
  - conda-forge
  - bioconda
dependencies:
  # min version dependencies based on the scanpy recipe
  - python >=3.9, <=3.10  # upper limit due to bioconda
  - python-igraph >=0.10
  - leidenalg >=0.10.2
  - matplotlib-base >=3.6
  - natsort
  - networkx >=2.7
  - numpy >=1.23
  - scanpy >=1.10

  # dev
  - black
  - isort
  - pytest
